/** @format */
import "./globals.css";
import type { Metadata } from "next";
import localFont from "next/font/local";
const iranSance = localFont({ src: "../public/fonts/iranSans.woff2" });
import AppProvider from "./lib/provider/app";
import Header from "./lib/design/layout/header";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="fa" dir="rtl">
      <body
        className={`${iranSance.className} bg-gray-100 text-black dark:bg-black
       dark:text-white capitalize`}
      >
        <AppProvider>
          <main>
            <Header />
            {children}
          </main>
        </AppProvider>
      </body>
    </html>
  );
}
